[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "paraphrase_gen"
version = "0.1.0"
description = "Paraphrase generation system"
authors = [{ name = "Daan I. Leiva" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []


[tool.setuptools.packages.find]
where = ["."]
include = ["paraphrase_gen*"]
